"""
Monte Carlo identification of the bias-correction factor b(n,r) for the
symmetrically truncated normal distribution.

For each truncation level r and sample size n, k = 2e8 samples are drawn from
N(0,1) truncated to [-r, r] (normalised to unit population standard deviation),
and b(n,r) is found such that the corrected estimator is unbiased:

    mean( sqrt( SSD / ((n - b(n,r)) * alpha(r)) ) ) = 1

where SSD is the sum of squared deviations of a sample and alpha(r) is the
population variance scaling factor of the truncated distribution. The whole
grid is evaluated R = 25 times with independent seeds to quantify the Monte
Carlo uncertainty of b(n,r).

Samples are generated by the inverse-CDF method (100% acceptance rate). Sample
sets are processed one n at a time to keep peak host memory near 2 GB; the
consolidated result of all completed repetitions is written to
optimal_brn_25reps.mat after every repetition.

Expected runtime: of order 100-300 h on a single CUDA GPU.
"""

import os
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'
os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION'] = '0.85'
os.environ['XLA_PYTHON_CLIENT_ALLOCATOR'] = 'platform'

import gc
import time
import traceback
import subprocess
from functools import partial
from datetime import datetime

import numpy as np
import scipy.io as sio
import jax
import jax.numpy as jnp
from jax import random, jit
from jax.scipy.special import erf, erfinv
from scipy.optimize import brentq

jax.config.update("jax_enable_x64", True)


def truncated_normal_std(r):
    """Population standard deviation of N(0,1) truncated to [-r, r]."""
    phi_r = (1.0 / np.sqrt(2.0 * np.pi)) * np.exp(-r**2 / 2.0)
    erf_val = float(erf(r / np.sqrt(2.0)))
    variance = 1.0 - 2.0 * r * phi_r / erf_val
    return np.sqrt(variance)


def get_gpu_memory():
    try:
        result = subprocess.run(
            ['nvidia-smi', '--query-gpu=name,memory.used,memory.total,memory.free',
             '--format=csv,noheader,nounits'],
            capture_output=True, text=True, timeout=5)
        if result.returncode != 0:
            return None, 0, 0, 0
        out = result.stdout.strip().split(',')
        if len(out) < 4:
            return None, 0, 0, 0
        return out[0].strip(), int(out[1]), int(out[2]), int(out[3])
    except Exception:
        return None, 0, 0, 0


@partial(jit, static_argnums=(1, 2, 3))
def generate_truncated_normal(key, n_samples, chunk_size, r):
    """Inverse-CDF sampler for N(0,1) truncated to [-r, r]; returns the sum of
    squared deviations of each of chunk_size samples of size n_samples."""
    uniform = random.uniform(key, shape=(n_samples * chunk_size,),
                             minval=0.0, maxval=1.0)
    sqrt2 = jnp.sqrt(2.0)
    cdf_lower = 0.5 * (1.0 + erf(-r / sqrt2))
    cdf_upper = 0.5 * (1.0 + erf(r / sqrt2))
    scaled = cdf_lower + uniform * (cdf_upper - cdf_lower)
    samples = (sqrt2 * erfinv(2.0 * scaled - 1.0)).reshape(n_samples, chunk_size)
    col_means = jnp.mean(samples, axis=0)
    return jnp.sum((samples - col_means[None, :]) ** 2, axis=0)


def squared_deviations_for_n(n, k, key, r, true_std, chunk_size):
    """Normalised sum of squared deviations for k samples of size n."""
    n_chunks = (k + chunk_size - 1) // chunk_size
    results = []
    for i in range(n_chunks):
        key, subkey = random.split(key)
        current = min(chunk_size, k - i * chunk_size)
        chunk = np.array(generate_truncated_normal(subkey, n, current, r)) / (true_std ** 2)
        results.append(chunk)
        if i % 500 == 0 and i > 0:
            gc.collect()
    out = np.concatenate(results)
    if len(out) != k:
        raise ValueError("expected %d values, got %d" % (k, len(out)))
    return out


def find_b(n, ssd):
    """Solve mean(sqrt(ssd / (n - b))) = 1 for b by Brent's method."""
    def objective(b):
        if n - b <= 0:
            return float('inf')
        return np.mean(np.sqrt(ssd / (n - b))) - 1.0
    try:
        return brentq(objective, 0.0, n - 0.1, xtol=1e-8)
    except ValueError:
        return n / 2.0


def compute_b_for_r(r, k, n_values, chunk_size, seed):
    """b(n,r) and the realised mean(s) for all n at one truncation level r."""
    true_std = truncated_normal_std(r)
    key = random.PRNGKey(seed)
    b_values = np.zeros(len(n_values))
    verification = np.zeros(len(n_values))
    for ni, n in enumerate(n_values):
        key, subkey = random.split(key)
        ssd = squared_deviations_for_n(n, k, subkey, r, true_std, chunk_size)
        b_values[ni] = find_b(n, ssd)
        verification[ni] = np.mean(np.sqrt(ssd / (n - b_values[ni])))
        del ssd
        gc.collect()
    return b_values, verification


def safe_chunk_size():
    _, _, total_mb, free_mb = get_gpu_memory()
    if total_mb == 0:
        return 5000000
    max_chunk = int((free_mb * 0.80 * 1024 * 1024) / (2 * 100 * 8 * 1.2))
    chunk = (max_chunk // 1000000) * 1000000
    return int(np.clip(chunk, 1000000, 20000000))


def save_results(filename, brn_matrix, verification_matrix, k, n, r_values,
                 n_repetitions):
    n_minus_brn = n[None, None, :] - brn_matrix
    sio.savemat(filename, {
        'k': k,
        'n': n,
        'r_values': r_values,
        'n_repetitions': n_repetitions,
        'brn_matrix': brn_matrix,
        'verification_matrix': verification_matrix,
        'n_minus_brn': n_minus_brn,
        'brn_description': 'brn_matrix[rep, i, j] = b(r_values[i], n[j])',
    }, do_compression=True)
    err = np.abs(verification_matrix - 1.0)
    print("  saved %s | reps=%d | max verification error=%.2e"
          % (filename, n_repetitions, np.max(err)))


def main():
    k = int(2e8)
    n = np.concatenate((np.arange(2, 31, 1),
                        np.arange(35, 51, 5),
                        np.arange(60, 101, 10)))
    r_values = np.concatenate((np.arange(0.2, 5.0 + 0.01, 0.1),
                               np.arange(5.5, 10.0 + 0.01, 0.5)))
    n_repetitions = 25
    out_file = 'optimal_brn_25reps.mat'

    print("Monte Carlo identification of b(n,r), truncated normal")
    print("  k          = %d samples per (n,r)" % k)
    print("  n          = %d values, %d to %d" % (len(n), n.min(), n.max()))
    print("  r          = %d values, %.2f to %.2f" % (len(r_values), r_values[0], r_values[-1]))
    print("  R          = %d repetitions" % n_repetitions)
    print("  method     = inverse CDF")
    print("  JAX %s, backend %s" % (jax.__version__, jax.default_backend()))
    print("  start      = %s" % datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

    chunk_size = safe_chunk_size()
    print("  chunk size = %d" % chunk_size)

    brn_matrix = np.zeros((n_repetitions, len(r_values), len(n)))
    verification_matrix = np.zeros((n_repetitions, len(r_values), len(n)))

    t0 = time.time()
    for rep in range(n_repetitions):
        t_rep = time.time()
        print("\nrepetition %d/%d" % (rep + 1, n_repetitions))
        for ri, r in enumerate(r_values):
            try:
                seed = 42 + rep * 1000 + ri
                b_values, verification = compute_b_for_r(r, k, n, chunk_size, seed)
                brn_matrix[rep, ri, :] = b_values
                verification_matrix[rep, ri, :] = verification
            except Exception as exc:
                print("  error at r=%.2f: %s" % (r, exc))
                traceback.print_exc()
                brn_matrix[rep, ri, :] = np.nan
                verification_matrix[rep, ri, :] = np.nan
            print("  r=%.2f done (%d/%d)" % (r, ri + 1, len(r_values)))
        elapsed = time.time() - t0
        print("repetition %d done in %.1f min, total %.1f h"
              % (rep + 1, (time.time() - t_rep) / 60, elapsed / 3600))
        # rolling save of all completed repetitions
        save_results(out_file, brn_matrix[:rep + 1], verification_matrix[:rep + 1],
                     k, n, r_values, rep + 1)

    print("\nall %d repetitions complete in %.1f h"
          % (n_repetitions, (time.time() - t0) / 3600))
    print("end = %s" % datetime.now().strftime('%Y-%m-%d %H:%M:%S'))


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\ninterrupted")
